import { Button, Form, Input } from "antd";
import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function SignIn() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Template</title>
        <meta content="Generated by create next app" name="description" />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
        <Form
          autoComplete="off"
          initialValues={{ remember: true }}
          labelCol={{ span: 4 }}
          name="basic"
          wrapperCol={{ span: 20 }}
        >
          <Form.Item wrapperCol={{ offset: 4, span: 20 }}>
            <h1>Sign In</h1>
          </Form.Item>
          <Form.Item
            label="Email"
            name="email"
            rules={[{ required: true, message: "Please input your email!" }]}
          >
            <Input />
          </Form.Item>

          <Form.Item
            label="Password"
            name="password"
            rules={[{ required: true, message: "Please input your password!" }]}
          >
            <Input.Password />
          </Form.Item>

          <Form.Item wrapperCol={{ offset: 4, span: 20 }}>
            <Button htmlType="submit" type="primary">
              Sign In
            </Button>
          </Form.Item>
        </Form>
      </main>
    </div>
  );
}
